### ISSUE TITLE
Optimize the D-Bus interface 

### ISSUE THREAD

**Issue by mardy** [ubports/hfd-service#22]
The service's D-Bus API is written in such a way that causes unnecessary D-Bus round trips. It should be rewritten to be a single method, taking several parameters at once: in this way clients wouldn't have to make several D-Bus call in sequence, as for instance is happening in Lomiri (from https://github.com/ubports/unity8/pull/414).

**Comment by Flohack74** [comment]
I agree that API is really strange unless that would be an industrial embedded controller with only low-level instruction set ;)

**Comment by peat-psuwit** [comment]
Hello,

Thank you for contributing to UBports. As part of project renaming and the effort to port Ubuntu Touch stack to Ubuntu 20.04, we're incrementally migrating repositories to GitLab.

Your issue is now migrated to:
https://gitlab.com/ubports/core/hfd-service/-/issues/2

Sorry for your inconvenience.
